"""Fix migrations after environment reset

Revision ID: 500d23fa502b
Revises: 87020b9cc6e3
Create Date: 2025-11-20 14:54:31.527852

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "500d23fa502b"
down_revision: Union[str, None] = "87020b9cc6e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
